sonar.projectKey=inventory-order-management
sonar.projectName=inventory-order-management
sonar.sources=app,public,config,scripts
sonar.tests=tests
sonar.exclusions=vendor/**,node_modules/**,public/assets/**
sonar.php.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=app/Controller/**,public/index.php,config/**,scripts/**